# Site settings
title: Embedded DB Junit Rule
email: zapodot@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Embedded DB Junit provides a JUnit Rule for embedding an H2 in memory database
  in your tests. The database is set up before your test (@Rule) or
  TestClass (@ClassRule) and is cleaned up afterwards. In essence, it makes it
  a lot easier to test your SQL and/or other database integration code.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://embedded-db-junit.zapodot.org" # the base hostname & protocol for your site
twitter_username: zapodot
github_username:  zapodot

# Build settings
markdown: kramdown

# Markdown processors
rdiscount:
  extensions: []

redcarpet:
    extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]
